### PR TITLE
ROUTEMOBILE GATEWAY

### PR DESCRIPTION
**Pull request by wddyousuf**

### CODE REVIEW

**Comment by arif98741** [comment]
Is this Bangladeshi sms provider?

**Comment by wddyousuf** [comment]
Global

**Comment by arif98741** [comment]
Laravelbdsms is made for serving only Bangladeshi sms providers. That's why I could not accept your pull request as well. By the way thanks for your contributions

**Comment by wddyousuf** [comment]
In Bangladesh,Many of us use this sms gateway..It is also used by our official site. Anyway thank you

**Pull request closed without merging**
